
import { ReactNode } from 'react';
import SessionProviderWrapper from '../components/SessionProviderWrapper'; // Adjust the import path if necessary

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <div className="text-gray-100 bg-black ">aaa</div>{children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}