import { render, screen, fireEvent } from '@testing-library/react';
import HomePage from './page';// Generated by CodiumAI

describe('HomePage', () => {

    // Renders without crashing
    it('should render without crashing', () => {
      const { container } = render(<HomePage />);
      expect(container).toBeInTheDocument();
    });
});